# Generated by Django 5.2.4 on 2025-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=1)),
            ],
        ),
    ]
