# Generated by Django 5.2.4 on 2025-07-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0003_alter_entry_options_entry_date_added_entry_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
