# Generated by Django 5.2.4 on 2025-08-06 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0006_meta_metatask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tasks', to='mytaskhubs.meta'),
        ),
        migrations.AlterField(
            model_name='metatask',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metatasks', to='mytaskhubs.meta'),
        ),
        migrations.AlterField(
            model_name='metatask',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='mytaskhubs.project'),
        ),
    ]
