# Generated by Django 5.2.4 on 2025-08-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0007_remove_task_description_task_completed_task_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mytaskhubs.meta'),
        ),
        migrations.DeleteModel(
            name='MetaTask',
        ),
    ]
