# Generated by Django 5.2.4 on 2025-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0010_meta_owner_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
