# Generated by Django 5.2.4 on 2025-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0011_rename_text_task_title_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
