# Generated by Django 5.2.4 on 2025-08-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0012_meta_completed_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meta',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
