# Generated by Django 5.2.4 on 2025-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0013_entry_deleted_meta_deleted_project_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='Sem descrição'),
        ),
    ]
