# Generated by Django 5.2.4 on 2025-09-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0014_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='title',
        ),
    ]
