# Generated by Django 5.2.4 on 2025-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskhubs', '0015_rename_text_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='text',
        ),
        migrations.AddField(
            model_name='meta',
            name='title',
            field=models.CharField(default='Título padrão', max_length=200),
            preserve_default=False,
        ),
    ]
